# Generated by Django 5.0.3 on 2024-03-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existen',
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('stock_inicial', models.PositiveIntegerField(default=0)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_venta', models.CharField(max_length=20, unique=True)),
                ('cantidad_vendida', models.PositiveIntegerField()),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
    ]
