# Generated by Django 5.0.3 on 2024-03-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_producto_existen_inventario_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_vendido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_venta', models.CharField(max_length=20, unique=True)),
                ('cantidad_vendida', models.PositiveIntegerField()),
                ('codigo_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
