# Generated by Django 5.0.3 on 2024-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_factura_producto_vendido_delete_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_vendido',
            name='comentario',
            field=models.CharField(blank=True, default='Producto vendido', max_length=200, null=True),
        ),
    ]
