# Generated by Django 5.0.3 on 2024-03-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_producto_vendido_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto_vendido',
            name='codigo_venta',
        ),
        migrations.AddField(
            model_name='producto_vendido',
            name='metodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.metodopago'),
        ),
    ]
