# Generated by Django 5.0.3 on 2024-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_metodopago_remove_producto_vendido_codigo_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_vendido',
            name='codigo_venta',
            field=models.CharField(default='001', max_length=20, unique=True),
        ),
    ]
