# Generated by Django 5.0.3 on 2024-03-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_producto_vendido_cantidad_vendida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_vendido',
            name='codigo_factura',
        ),
        migrations.RemoveField(
            model_name='producto_vendido',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='producto_vendido',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Producto_vendido',
        ),
    ]
