# Generated by Django 5.0.3 on 2024-03-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_remove_producto_vendido_codigo_factura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_factura', models.CharField(max_length=50)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_vendido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_venta', models.CharField(max_length=20, unique=True)),
                ('cantidad_vendida', models.PositiveIntegerField()),
                ('comentario', models.CharField(blank=True, default='Venta Añadida', max_length=200, null=True)),
                ('codigo_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.factura')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodopago')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
    ]
