# Generated by Django 5.0.3 on 2024-03-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_remove_producto_vendido_codigo_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto_vendido',
        ),
    ]
