# Generated by Django 5.0.3 on 2024-03-24 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_delete_producto_vendido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Productos_Factura',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vendida', models.PositiveIntegerField()),
                ('codigo_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_Productos_Factura',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, default='Venta Añadida', max_length=200, null=True)),
                ('total', models.PositiveIntegerField()),
                ('lista_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.lista_productos_factura')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.metodopago')),
            ],
        ),
    ]
