# Generated by Django 5.0.3 on 2024-03-24 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_lista_productos_factura_venta_productos_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta_productos_factura',
            name='lista_productos',
        ),
        migrations.AddField(
            model_name='venta_productos_factura',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura'),
        ),
    ]
