# Generated by Django 5.0.3 on 2024-04-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_historial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='historial',
        ),
    ]
