# Generated by Django 5.0.3 on 2024-04-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_delete_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('venta', models.CharField(max_length=200)),
                ('productos', models.TextField()),
                ('total', models.IntegerField()),
                ('metodo', models.CharField(max_length=50)),
            ],
        ),
    ]
