# Generated by Django 5.0.3 on 2024-04-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_productosinunidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productosinunidad',
            old_name='stock_en_gramos',
            new_name='stock_en_kilos',
        ),
    ]
